package com.blackstar.model;

// Generated Sep 23, 2013 12:57:18 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Office generated by hbm2java
 */
@Entity
@Table(name = "office", catalog = "blackstarDb")
public class Office implements java.io.Serializable {

	private char officeId;
	private String officeName;

	public Office() {
	}

	public Office(char officeId) {
		this.officeId = officeId;
	}

	public Office(char officeId, String officeName) {
		this.officeId = officeId;
		this.officeName = officeName;
	}

	@Id
	@Column(name = "officeId", unique = true, nullable = false, length = 1)
	public char getOfficeId() {
		return this.officeId;
	}

	public void setOfficeId(char officeId) {
		this.officeId = officeId;
	}

	@Column(name = "officeName", length = 50)
	public String getOfficeName() {
		return this.officeName;
	}

	public void setOfficeName(String officeName) {
		this.officeName = officeName;
	}

}
