package com.blackstar.model;

// Generated Sep 23, 2013 12:57:18 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Policytype generated by hbm2java
 */
@Entity
@Table(name = "policytype", catalog = "blackstarDb")
public class Policytype implements java.io.Serializable {

	private char policyTypeId;
	private String policyType;

	public Policytype() {
	}

	public Policytype(char policyTypeId, String policyType) {
		this.policyTypeId = policyTypeId;
		this.policyType = policyType;
	}

	@Id
	@Column(name = "policyTypeId", unique = true, nullable = false, length = 1)
	public char getPolicyTypeId() {
		return this.policyTypeId;
	}

	public void setPolicyTypeId(char policyTypeId) {
		this.policyTypeId = policyTypeId;
	}

	@Column(name = "policyType", nullable = false, length = 50)
	public String getPolicyType() {
		return this.policyType;
	}

	public void setPolicyType(String policyType) {
		this.policyType = policyType;
	}

}
