package com.blackstar.model;

// Generated 19/09/2013 02:56:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Policycontact generated by hbm2java
 */
public class Policycontact implements java.io.Serializable {

	private int policyContactId;
	private String name;
	private String phone;
	private String email;
	private Date created;
	private String createdBy;
	private String createdByUsr;
	private Date modified;
	private String modifiedBy;
	private String modifiedByUsr;

	public Policycontact() {
	}

	public Policycontact(int policyContactId, String name) {
		this.policyContactId = policyContactId;
		this.name = name;
	}

	public Policycontact(int policyContactId, String name, String phone,
			String email, Date created, String createdBy, String createdByUsr,
			Date modified, String modifiedBy, String modifiedByUsr) {
		this.policyContactId = policyContactId;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.created = created;
		this.createdBy = createdBy;
		this.createdByUsr = createdByUsr;
		this.modified = modified;
		this.modifiedBy = modifiedBy;
		this.modifiedByUsr = modifiedByUsr;
	}

	public int getPolicyContactId() {
		return this.policyContactId;
	}

	public void setPolicyContactId(int policyContactId) {
		this.policyContactId = policyContactId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getCreatedByUsr() {
		return this.createdByUsr;
	}

	public void setCreatedByUsr(String createdByUsr) {
		this.createdByUsr = createdByUsr;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getModifiedByUsr() {
		return this.modifiedByUsr;
	}

	public void setModifiedByUsr(String modifiedByUsr) {
		this.modifiedByUsr = modifiedByUsr;
	}

}
