package com.blackstar.model;

// Generated 19/09/2013 02:56:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Policy generated by hbm2java
 */
public class Policy implements java.io.Serializable {

	private Integer policyId;
	private char officeId;
	private char policyTypeId;
	private String customerContract;
	private String customer;
	private String finalUser;
	private String project;
	private String cst;
	private Character equipmentTypeId;
	private String brand;
	private String model;
	private String serialNumber;
	private String capacity;
	private String equipmentAddress;
	private String equipmentLocation;
	private Integer policyContactId;
	private Date startDate;
	private Date endDate;
	private Integer visitsPerYear;
	private Byte responseTimeHr;
	private Short solutionTimeHr;
	private String penalty;
	private String service;
	private byte includesParts;
	private String exceptionParts;
	private Character serviceCenterId;
	private String observations;
	private Date created;
	private String createdBy;
	private String crratedByUsr;
	private Date modified;
	private String modifiedBy;
	private String modifiedByUsr;

	public Policy() {
	}

	public Policy(char officeId, char policyTypeId, byte includesParts) {
		this.officeId = officeId;
		this.policyTypeId = policyTypeId;
		this.includesParts = includesParts;
	}

	public Policy(char officeId, char policyTypeId, String customerContract,
			String customer, String finalUser, String project, String cst,
			Character equipmentTypeId, String brand, String model,
			String serialNumber, String capacity, String equipmentAddress,
			String equipmentLocation, Integer policyContactId, Date startDate,
			Date endDate, Integer visitsPerYear, Byte responseTimeHr,
			Short solutionTimeHr, String penalty, String service,
			byte includesParts, String exceptionParts,
			Character serviceCenterId, String observations, Date created,
			String createdBy, String crratedByUsr, Date modified,
			String modifiedBy, String modifiedByUsr) {
		this.officeId = officeId;
		this.policyTypeId = policyTypeId;
		this.customerContract = customerContract;
		this.customer = customer;
		this.finalUser = finalUser;
		this.project = project;
		this.cst = cst;
		this.equipmentTypeId = equipmentTypeId;
		this.brand = brand;
		this.model = model;
		this.serialNumber = serialNumber;
		this.capacity = capacity;
		this.equipmentAddress = equipmentAddress;
		this.equipmentLocation = equipmentLocation;
		this.policyContactId = policyContactId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.visitsPerYear = visitsPerYear;
		this.responseTimeHr = responseTimeHr;
		this.solutionTimeHr = solutionTimeHr;
		this.penalty = penalty;
		this.service = service;
		this.includesParts = includesParts;
		this.exceptionParts = exceptionParts;
		this.serviceCenterId = serviceCenterId;
		this.observations = observations;
		this.created = created;
		this.createdBy = createdBy;
		this.crratedByUsr = crratedByUsr;
		this.modified = modified;
		this.modifiedBy = modifiedBy;
		this.modifiedByUsr = modifiedByUsr;
	}

	public Integer getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	public char getOfficeId() {
		return this.officeId;
	}

	public void setOfficeId(char officeId) {
		this.officeId = officeId;
	}

	public char getPolicyTypeId() {
		return this.policyTypeId;
	}

	public void setPolicyTypeId(char policyTypeId) {
		this.policyTypeId = policyTypeId;
	}

	public String getCustomerContract() {
		return this.customerContract;
	}

	public void setCustomerContract(String customerContract) {
		this.customerContract = customerContract;
	}

	public String getCustomer() {
		return this.customer;
	}

	public void setCustomer(String customer) {
		this.customer = customer;
	}

	public String getFinalUser() {
		return this.finalUser;
	}

	public void setFinalUser(String finalUser) {
		this.finalUser = finalUser;
	}

	public String getProject() {
		return this.project;
	}

	public void setProject(String project) {
		this.project = project;
	}

	public String getCst() {
		return this.cst;
	}

	public void setCst(String cst) {
		this.cst = cst;
	}

	public Character getEquipmentTypeId() {
		return this.equipmentTypeId;
	}

	public void setEquipmentTypeId(Character equipmentTypeId) {
		this.equipmentTypeId = equipmentTypeId;
	}

	public String getBrand() {
		return this.brand;
	}

	public void setBrand(String brand) {
		this.brand = brand;
	}

	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public String getCapacity() {
		return this.capacity;
	}

	public void setCapacity(String capacity) {
		this.capacity = capacity;
	}

	public String getEquipmentAddress() {
		return this.equipmentAddress;
	}

	public void setEquipmentAddress(String equipmentAddress) {
		this.equipmentAddress = equipmentAddress;
	}

	public String getEquipmentLocation() {
		return this.equipmentLocation;
	}

	public void setEquipmentLocation(String equipmentLocation) {
		this.equipmentLocation = equipmentLocation;
	}

	public Integer getPolicyContactId() {
		return this.policyContactId;
	}

	public void setPolicyContactId(Integer policyContactId) {
		this.policyContactId = policyContactId;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public Integer getVisitsPerYear() {
		return this.visitsPerYear;
	}

	public void setVisitsPerYear(Integer visitsPerYear) {
		this.visitsPerYear = visitsPerYear;
	}

	public Byte getResponseTimeHr() {
		return this.responseTimeHr;
	}

	public void setResponseTimeHr(Byte responseTimeHr) {
		this.responseTimeHr = responseTimeHr;
	}

	public Short getSolutionTimeHr() {
		return this.solutionTimeHr;
	}

	public void setSolutionTimeHr(Short solutionTimeHr) {
		this.solutionTimeHr = solutionTimeHr;
	}

	public String getPenalty() {
		return this.penalty;
	}

	public void setPenalty(String penalty) {
		this.penalty = penalty;
	}

	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	public byte getIncludesParts() {
		return this.includesParts;
	}

	public void setIncludesParts(byte includesParts) {
		this.includesParts = includesParts;
	}

	public String getExceptionParts() {
		return this.exceptionParts;
	}

	public void setExceptionParts(String exceptionParts) {
		this.exceptionParts = exceptionParts;
	}

	public Character getServiceCenterId() {
		return this.serviceCenterId;
	}

	public void setServiceCenterId(Character serviceCenterId) {
		this.serviceCenterId = serviceCenterId;
	}

	public String getObservations() {
		return this.observations;
	}

	public void setObservations(String observations) {
		this.observations = observations;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getCrratedByUsr() {
		return this.crratedByUsr;
	}

	public void setCrratedByUsr(String crratedByUsr) {
		this.crratedByUsr = crratedByUsr;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getModifiedByUsr() {
		return this.modifiedByUsr;
	}

	public void setModifiedByUsr(String modifiedByUsr) {
		this.modifiedByUsr = modifiedByUsr;
	}

}
