package com.blackstar.model;

// Generated 19/09/2013 02:56:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Serviceorder generated by hbm2java
 */
public class Serviceorder implements java.io.Serializable {

	private Integer serviceOrderId;
	private Character serviceTypeId;
	private Integer ticketId;
	private Short policyId;
	private String serviceUnit;
	private Date serviceDate;
	private String responsible;
	private String receivedBy;
	private String serviceComments;
	private Byte statusId;
	private Date closed;
	private String consultant;
	private String coordinator;
	private String asignee;
	private Date created;
	private String createdBy;
	private String createdByUsr;
	private Date modified;
	private String modifiedBy;
	private String modifiedByUsr;

	public Serviceorder() {
	}

	public Serviceorder(Character serviceTypeId, Integer ticketId,
			Short policyId, String serviceUnit, Date serviceDate,
			String responsible, String receivedBy, String serviceComments,
			Byte statusId, Date closed, String consultant, String coordinator,
			String asignee, Date created, String createdBy,
			String createdByUsr, Date modified, String modifiedBy,
			String modifiedByUsr) {
		this.serviceTypeId = serviceTypeId;
		this.ticketId = ticketId;
		this.policyId = policyId;
		this.serviceUnit = serviceUnit;
		this.serviceDate = serviceDate;
		this.responsible = responsible;
		this.receivedBy = receivedBy;
		this.serviceComments = serviceComments;
		this.statusId = statusId;
		this.closed = closed;
		this.consultant = consultant;
		this.coordinator = coordinator;
		this.asignee = asignee;
		this.created = created;
		this.createdBy = createdBy;
		this.createdByUsr = createdByUsr;
		this.modified = modified;
		this.modifiedBy = modifiedBy;
		this.modifiedByUsr = modifiedByUsr;
	}

	public Integer getServiceOrderId() {
		return this.serviceOrderId;
	}

	public void setServiceOrderId(Integer serviceOrderId) {
		this.serviceOrderId = serviceOrderId;
	}

	public Character getServiceTypeId() {
		return this.serviceTypeId;
	}

	public void setServiceTypeId(Character serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	public Short getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(Short policyId) {
		this.policyId = policyId;
	}

	public String getServiceUnit() {
		return this.serviceUnit;
	}

	public void setServiceUnit(String serviceUnit) {
		this.serviceUnit = serviceUnit;
	}

	public Date getServiceDate() {
		return this.serviceDate;
	}

	public void setServiceDate(Date serviceDate) {
		this.serviceDate = serviceDate;
	}

	public String getResponsible() {
		return this.responsible;
	}

	public void setResponsible(String responsible) {
		this.responsible = responsible;
	}

	public String getReceivedBy() {
		return this.receivedBy;
	}

	public void setReceivedBy(String receivedBy) {
		this.receivedBy = receivedBy;
	}

	public String getServiceComments() {
		return this.serviceComments;
	}

	public void setServiceComments(String serviceComments) {
		this.serviceComments = serviceComments;
	}

	public Byte getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Byte statusId) {
		this.statusId = statusId;
	}

	public Date getClosed() {
		return this.closed;
	}

	public void setClosed(Date closed) {
		this.closed = closed;
	}

	public String getConsultant() {
		return this.consultant;
	}

	public void setConsultant(String consultant) {
		this.consultant = consultant;
	}

	public String getCoordinator() {
		return this.coordinator;
	}

	public void setCoordinator(String coordinator) {
		this.coordinator = coordinator;
	}

	public String getAsignee() {
		return this.asignee;
	}

	public void setAsignee(String asignee) {
		this.asignee = asignee;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getCreatedByUsr() {
		return this.createdByUsr;
	}

	public void setCreatedByUsr(String createdByUsr) {
		this.createdByUsr = createdByUsr;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getModifiedByUsr() {
		return this.modifiedByUsr;
	}

	public void setModifiedByUsr(String modifiedByUsr) {
		this.modifiedByUsr = modifiedByUsr;
	}

}
