package com.blackstar.model;

// Generated Sep 23, 2013 12:57:18 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servicetype generated by hbm2java
 */
@Entity
@Table(name = "servicetype", catalog = "blackstarDb")
public class Servicetype implements java.io.Serializable {

	private char serviceTypeId;
	private String serviceType;

	public Servicetype() {
	}

	public Servicetype(char serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	public Servicetype(char serviceTypeId, String serviceType) {
		this.serviceTypeId = serviceTypeId;
		this.serviceType = serviceType;
	}

	@Id
	@Column(name = "serviceTypeId", unique = true, nullable = false, length = 1)
	public char getServiceTypeId() {
		return this.serviceTypeId;
	}

	public void setServiceTypeId(char serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	@Column(name = "serviceType", length = 50)
	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

}
