package com.blackstar.model;

// Generated 19/09/2013 02:56:42 AM by Hibernate Tools 3.4.0.CR1

/**
 * Servicecenter generated by hbm2java
 */
public class Servicecenter implements java.io.Serializable {

	private char serviceCenterId;
	private String serviceCenter;

	public Servicecenter() {
	}

	public Servicecenter(char serviceCenterId, String serviceCenter) {
		this.serviceCenterId = serviceCenterId;
		this.serviceCenter = serviceCenter;
	}

	public char getServiceCenterId() {
		return this.serviceCenterId;
	}

	public void setServiceCenterId(char serviceCenterId) {
		this.serviceCenterId = serviceCenterId;
	}

	public String getServiceCenter() {
		return this.serviceCenter;
	}

	public void setServiceCenter(String serviceCenter) {
		this.serviceCenter = serviceCenter;
	}

}
