package com.blackstar.model;

// Generated 19/09/2013 02:56:42 AM by Hibernate Tools 3.4.0.CR1

/**
 * Servicetype generated by hbm2java
 */
public class Servicetype implements java.io.Serializable {

	private char serviceTypeId;
	private String serviceType;

	public Servicetype() {
	}

	public Servicetype(char serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	public Servicetype(char serviceTypeId, String serviceType) {
		this.serviceTypeId = serviceTypeId;
		this.serviceType = serviceType;
	}

	public char getServiceTypeId() {
		return this.serviceTypeId;
	}

	public void setServiceTypeId(char serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	public String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(String serviceType) {
		this.serviceType = serviceType;
	}

}
