package com.blackstar.model;

// Generated Sep 23, 2013 12:57:18 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Serviceorder generated by hbm2java
 */
@Entity
@Table(name = "serviceorder", catalog = "blackstarDb")
public class Serviceorder implements java.io.Serializable {

	private Integer serviceOrderId;
	private Character serviceTypeId;
	private Integer ticketId;
	private Short policyId;
	private String serviceUnit;
	private Date serviceDate;
	private String responsible;
	private String receivedBy;
	private String serviceComments;
	private Byte statusId;
	private Date closed;
	private String consultant;
	private String coordinator;
	private String asignee;
	private Date created;
	private String createdBy;
	private String createdByUsr;
	private Date modified;
	private String modifiedBy;
	private String modifiedByUsr;
	private String firmaRealizado;
	private String firmaRecibido;

	public Serviceorder() {
	}

	public Serviceorder(Character serviceTypeId, Integer ticketId,
			Short policyId, String serviceUnit, Date serviceDate,
			String responsible, String receivedBy, String serviceComments,
			Byte statusId, Date closed, String consultant, String coordinator,
			String asignee, Date created, String createdBy,
			String createdByUsr, Date modified, String modifiedBy,
			String modifiedByUsr, String firmaRealizado, String firmaRecibido) {
		this.serviceTypeId = serviceTypeId;
		this.ticketId = ticketId;
		this.policyId = policyId;
		this.serviceUnit = serviceUnit;
		this.serviceDate = serviceDate;
		this.responsible = responsible;
		this.receivedBy = receivedBy;
		this.serviceComments = serviceComments;
		this.statusId = statusId;
		this.closed = closed;
		this.consultant = consultant;
		this.coordinator = coordinator;
		this.asignee = asignee;
		this.created = created;
		this.createdBy = createdBy;
		this.createdByUsr = createdByUsr;
		this.modified = modified;
		this.modifiedBy = modifiedBy;
		this.modifiedByUsr = modifiedByUsr;
		this.firmaRealizado = firmaRealizado;
		this.firmaRecibido = firmaRecibido;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "serviceOrderId", unique = true, nullable = false)
	public Integer getServiceOrderId() {
		return this.serviceOrderId;
	}

	public void setServiceOrderId(Integer serviceOrderId) {
		this.serviceOrderId = serviceOrderId;
	}

	@Column(name = "serviceTypeId", length = 1)
	public Character getServiceTypeId() {
		return this.serviceTypeId;
	}

	public void setServiceTypeId(Character serviceTypeId) {
		this.serviceTypeId = serviceTypeId;
	}

	@Column(name = "ticketId")
	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	@Column(name = "policyId")
	public Short getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(Short policyId) {
		this.policyId = policyId;
	}

	@Column(name = "serviceUnit", length = 10)
	public String getServiceUnit() {
		return this.serviceUnit;
	}

	public void setServiceUnit(String serviceUnit) {
		this.serviceUnit = serviceUnit;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "serviceDate", length = 19)
	public Date getServiceDate() {
		return this.serviceDate;
	}

	public void setServiceDate(Date serviceDate) {
		this.serviceDate = serviceDate;
	}

	@Column(name = "responsible", length = 100)
	public String getResponsible() {
		return this.responsible;
	}

	public void setResponsible(String responsible) {
		this.responsible = responsible;
	}

	@Column(name = "receivedBy", length = 100)
	public String getReceivedBy() {
		return this.receivedBy;
	}

	public void setReceivedBy(String receivedBy) {
		this.receivedBy = receivedBy;
	}

	@Column(name = "serviceComments", length = 65535)
	public String getServiceComments() {
		return this.serviceComments;
	}

	public void setServiceComments(String serviceComments) {
		this.serviceComments = serviceComments;
	}

	@Column(name = "statusId")
	public Byte getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Byte statusId) {
		this.statusId = statusId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "closed", length = 19)
	public Date getClosed() {
		return this.closed;
	}

	public void setClosed(Date closed) {
		this.closed = closed;
	}

	@Column(name = "consultant", length = 100)
	public String getConsultant() {
		return this.consultant;
	}

	public void setConsultant(String consultant) {
		this.consultant = consultant;
	}

	@Column(name = "coordinator", length = 100)
	public String getCoordinator() {
		return this.coordinator;
	}

	public void setCoordinator(String coordinator) {
		this.coordinator = coordinator;
	}

	@Column(name = "asignee", length = 50)
	public String getAsignee() {
		return this.asignee;
	}

	public void setAsignee(String asignee) {
		this.asignee = asignee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "createdBy", length = 50)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "createdByUsr", length = 50)
	public String getCreatedByUsr() {
		return this.createdByUsr;
	}

	public void setCreatedByUsr(String createdByUsr) {
		this.createdByUsr = createdByUsr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modified", length = 19)
	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	@Column(name = "modifiedBy", length = 50)
	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	@Column(name = "modifiedByUsr", length = 50)
	public String getModifiedByUsr() {
		return this.modifiedByUsr;
	}

	public void setModifiedByUsr(String modifiedByUsr) {
		this.modifiedByUsr = modifiedByUsr;
	}
	
	@Column(name = "firmaRealizado", length = 50)
	public String getFirmaRealizado() {
		return this.firmaRealizado;
	}

	public void setfirmaRealizado(String firmaRealizado) {
		this.firmaRealizado = firmaRealizado;
	}
	
	@Column(name = "firmaRecibido", length = 50)
	public String getFirmaRecibido() {
		return this.firmaRecibido;
	}

	public void setFirmaRecibido(String firmaRecibido) {
		this.firmaRecibido = firmaRecibido;
	}

}
