package com.blackstar.model;

// Generated Sep 23, 2013 12:57:18 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Servicecenter generated by hbm2java
 */
@Entity
@Table(name = "servicecenter", catalog = "blackstarDb")
public class Servicecenter implements java.io.Serializable {

	private char serviceCenterId;
	private String serviceCenter;
	private String serviceCenterEmail;

	public Servicecenter() {
	}

	public Servicecenter(char serviceCenterId, String serviceCenter, String serviceCenterEmail) {
		this.serviceCenterId = serviceCenterId;
		this.serviceCenter = serviceCenter;
		this.serviceCenterEmail = serviceCenterEmail;
	}

	@Id
	@Column(name = "serviceCenterId", unique = true, nullable = false, length = 1)
	public char getServiceCenterId() {
		return this.serviceCenterId;
	}

	public void setServiceCenterId(char serviceCenterId) {
		this.serviceCenterId = serviceCenterId;
	}

	@Column(name = "serviceCenter", nullable = false, length = 100)
	public String getServiceCenter() {
		return this.serviceCenter;
	}

	public void setServiceCenter(String serviceCenter) {
		this.serviceCenter = serviceCenter;
	}

	public String getServiceCenterEmail() {
		return serviceCenterEmail;
	}

	public void setServiceCenterEmail(String serviceCenterEmail) {
		this.serviceCenterEmail = serviceCenterEmail;
	}

}
