package com.blackstar.model;

// Generated Sep 23, 2013 12:57:18 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ticketstatus generated by hbm2java
 */
@Entity
@Table(name = "ticketstatus", catalog = "blackstarDb")
public class Ticketstatus implements java.io.Serializable {

	private char ticketStatusId;
	private String ticketStatus;

	public Ticketstatus() {
	}

	public Ticketstatus(char ticketStatusId) {
		this.ticketStatusId = ticketStatusId;
	}

	public Ticketstatus(char ticketStatusId, String ticketStatus) {
		this.ticketStatusId = ticketStatusId;
		this.ticketStatus = ticketStatus;
	}

	@Id
	@Column(name = "ticketStatusId", unique = true, nullable = false, length = 1)
	public char getTicketStatusId() {
		return this.ticketStatusId;
	}

	public void setTicketStatusId(char ticketStatusId) {
		this.ticketStatusId = ticketStatusId;
	}

	@Column(name = "ticketStatus", length = 50)
	public String getTicketStatus() {
		return this.ticketStatus;
	}

	public void setTicketStatus(String ticketStatus) {
		this.ticketStatus = ticketStatus;
	}

}
