package com.blackstar.model;

// Generated 19/09/2013 02:56:42 AM by Hibernate Tools 3.4.0.CR1

/**
 * Ticketstatus generated by hbm2java
 */
public class Ticketstatus implements java.io.Serializable {

	private char ticketStatusId;
	private String ticketStatus;

	public Ticketstatus() {
	}

	public Ticketstatus(char ticketStatusId) {
		this.ticketStatusId = ticketStatusId;
	}

	public Ticketstatus(char ticketStatusId, String ticketStatus) {
		this.ticketStatusId = ticketStatusId;
		this.ticketStatus = ticketStatus;
	}

	public char getTicketStatusId() {
		return this.ticketStatusId;
	}

	public void setTicketStatusId(char ticketStatusId) {
		this.ticketStatusId = ticketStatusId;
	}

	public String getTicketStatus() {
		return this.ticketStatus;
	}

	public void setTicketStatus(String ticketStatus) {
		this.ticketStatus = ticketStatus;
	}

}
