package com.blackstar.model;

// Generated 19/09/2013 02:56:42 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Ticket generated by hbm2java
 */
public class Ticket implements java.io.Serializable {

	private Integer ticketId;
	private Integer policyId;
	private Short serviceId;
	private String user;
	private String observations;
	private Character ticketStatusId;
	private Short realResponseTime;
	private Date arrival;
	private Long employee;
	private String asignee;
	private Date closed;
	private Date solutionTime;
	private Short solutionTimeDeviationHr;
	private Date created;
	private String createdBy;
	private String createdByUsr;
	private Date modified;
	private String modifiedBy;
	private String modifiedByUsr;

	public Ticket() {
	}

	public Ticket(Integer policyId, Short serviceId, String user,
			String observations, Character ticketStatusId,
			Short realResponseTime, Date arrival, Long employee,
			String asignee, Date closed, Date solutionTime,
			Short solutionTimeDeviationHr, Date created, String createdBy,
			String createdByUsr, Date modified, String modifiedBy,
			String modifiedByUsr) {
		this.policyId = policyId;
		this.serviceId = serviceId;
		this.user = user;
		this.observations = observations;
		this.ticketStatusId = ticketStatusId;
		this.realResponseTime = realResponseTime;
		this.arrival = arrival;
		this.employee = employee;
		this.asignee = asignee;
		this.closed = closed;
		this.solutionTime = solutionTime;
		this.solutionTimeDeviationHr = solutionTimeDeviationHr;
		this.created = created;
		this.createdBy = createdBy;
		this.createdByUsr = createdByUsr;
		this.modified = modified;
		this.modifiedBy = modifiedBy;
		this.modifiedByUsr = modifiedByUsr;
	}

	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	public Integer getPolicyId() {
		return this.policyId;
	}

	public void setPolicyId(Integer policyId) {
		this.policyId = policyId;
	}

	public Short getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Short serviceId) {
		this.serviceId = serviceId;
	}

	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getObservations() {
		return this.observations;
	}

	public void setObservations(String observations) {
		this.observations = observations;
	}

	public Character getTicketStatusId() {
		return this.ticketStatusId;
	}

	public void setTicketStatusId(Character ticketStatusId) {
		this.ticketStatusId = ticketStatusId;
	}

	public Short getRealResponseTime() {
		return this.realResponseTime;
	}

	public void setRealResponseTime(Short realResponseTime) {
		this.realResponseTime = realResponseTime;
	}

	public Date getArrival() {
		return this.arrival;
	}

	public void setArrival(Date arrival) {
		this.arrival = arrival;
	}

	public Long getEmployee() {
		return this.employee;
	}

	public void setEmployee(Long employee) {
		this.employee = employee;
	}

	public String getAsignee() {
		return this.asignee;
	}

	public void setAsignee(String asignee) {
		this.asignee = asignee;
	}

	public Date getClosed() {
		return this.closed;
	}

	public void setClosed(Date closed) {
		this.closed = closed;
	}

	public Date getSolutionTime() {
		return this.solutionTime;
	}

	public void setSolutionTime(Date solutionTime) {
		this.solutionTime = solutionTime;
	}

	public Short getSolutionTimeDeviationHr() {
		return this.solutionTimeDeviationHr;
	}

	public void setSolutionTimeDeviationHr(Short solutionTimeDeviationHr) {
		this.solutionTimeDeviationHr = solutionTimeDeviationHr;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public String getCreatedByUsr() {
		return this.createdByUsr;
	}

	public void setCreatedByUsr(String createdByUsr) {
		this.createdByUsr = createdByUsr;
	}

	public Date getModified() {
		return this.modified;
	}

	public void setModified(Date modified) {
		this.modified = modified;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getModifiedByUsr() {
		return this.modifiedByUsr;
	}

	public void setModifiedByUsr(String modifiedByUsr) {
		this.modifiedByUsr = modifiedByUsr;
	}

}
